export const ERROR_CODES = {
  // 공통
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // 도메인별
  STUDY_NOT_FOUND: "STUDY_NOT_FOUND",
  HABIT_NOT_FOUND: "HABIT_NOT_FOUND",
  HABIT_LOG_NOT_FOUND: "HABIT_LOG_NOT_FOUND",
  FOCUS_NOT_FOUND: "FOCUS_NOT_FOUND",

  DUPLICATE_FOCUS_TITLE: "DUPLICATE_FOCUS_TITLE",
  FOCUS_ALREADY_COMPLETED: "FOCUS_ALREADY_COMPLETED",
};
